### ISSUE TITLE
App title

### ISSUE THREAD

**Issue by avive** [karma-coin/apps#1]
Please change main page title from `Polkadot/Substrate Portal` to `Karma Coin Portal`.

![Screenshot 2023-06-13 at 2 43 34 PM](https://github.com/karma-coin/apps/assets/96002/7b68a59a-9028-4ef6-af34-47ebccbdab7d)

**Comment by HolyGrease** [comment]
Done in eea3c4b891126cb453bd2c0cab30aa957495c941
